#!/bin/bash

cd $(dirname $0)/..

if [ -z "$VIRTUAL_ENV" ];then
    echo "Not in Virtualenv creating..."
    if [ ! `command -v virtualenv` ];then
        curl -O https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.11.6.tar.gz
        tar xvfz virtualenv-1.11.6.tar.gz
        python ./virtualenv-1.11.6/virtualenv.py .env
    else
        virtualenv .env
    fi
    . ./.env/bin/activate
fi

pip install -r test-requirements.txt
